version: '3.1'

services:
  sl:
    container_name: sl
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 8002:8002
    command: streamlit run main.py --server.port=8002 --server.address=0.0.0.0
