version: '3.1'

services:
  stremlit:
    container_name: stremlit_server
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    command: stremlit run main.py --server.port=8001 --server.address=0.0.0.0.