version: '3.1'

services:
  streamlit:
    container_name: streamlit
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 8002:8002
    command: streamlit run main.py --server.port=8001 --server.address=0.0.0.0
