name: EC2
on: push
jobs:
  deploy:
    name: First
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_v1 }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-18-188-203-126.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/bilenko/streamlit"
